const express = require('express')
const router = express.Router()
const SachController = require('../controllers/sach.controller')
const {verifyTokenStaff} = require('../middlewares/verifyToken')
router.get('/', SachController.getAll)
    .post('/', verifyTokenStaff, SachController.addBook)
    .patch('/:MaSach', verifyTokenStaff, SachController.updateBook)
    .delete('/:MaSach', verifyTokenStaff, SachController.deleteBook)
    .delete('/', verifyTokenStaff, SachController.deleteAllBook)
module.exports = router